const route = {
    shoplist : 'sp://shoplist/shoplist',
    search : 'sp://search/search',
    activity : 'sp://activity/activity',
    category : 'sp://category/category',
    goodDetail : 'sp://goodDetail/goodDetail',
    chat : 'sp://chat/chat',
    myIntegral : 'sp://myIntegral/myIntegral',
    home : 'sp://home/home',
    login : 'sp://login/login',
    help : 'sp://help/help',
    message : 'sp://message/message',
    myAdress : 'sp://myAdress/myAdress',
    myCash : 'sp://myCash/myCash',
    myLike : 'sp://myLike/myLike',
    myOrder : 'sp://myOrder/myOrder',
    myProfile : 'sp://myProfile/myProfile',
    myTicket : 'sp://myTicket/myTicket',
    newFeatures : 'sp://newFeatures/newFeatures',
    orderDetail : 'sp://orderDetail/orderDetail',
    payBefore : 'sp://payBefore/payBefore',
    shopCart : 'sp://shopCart/shopCart',
    shopDetail : 'sp://shopDetail/shopDetail',
    summon : 'sp://summon/summon',
    map : 'sp://map/map',
    videoPlayer : 'sp://videoPlayer/videoPlayer'
}